Fix #287
cpanel/elevate pull request #289
Opened 2023-07-03 18:22 UTC by troglodyne

Since this is a bug in cPanel v110 or earlier, there's really no reasonable expectation to fix this anywhere but "in the mix" so just enable MySQL before performing the upgrade so that it does not fail. If it was disabled previously, re-disable it upon upgrade completion, however that winds up falling out.

By submitting pull requests to this repo, I agree to the Contributor License Agreement which can be found at: https://github.com/cpanel/elevate/blob/main/docs/cPanel-CLA.pdf

2023-07-05 20:20 UTC, atoomic commented on lib/Elevate/Components/MySQL.pm
> +    my $enabled = Cpanel::Services::Enabled::is_enabled('mysql');
let's store that status to the elevate status file so we can reuse that state later when reinstalling/restarting MySQL and do not block on it when disabled

2023-07-05 20:24 UTC, toddr commented on lib/Elevate/Components/MySQL.pm
> +            if($?) {
We don't want to die even if it fails if it was disabled to begin with.

2023-07-05 20:25 UTC, atoomic commented on lib/Elevate/Components/MySQL.pm
> +
what if the elevate process crash and we have to run `--continue` from there, we will use an incorrect state

2023-07-05 20:27 UTC, atoomic requested changes
let's capture state or use a blocker?

2023-07-06 16:28 UTC, troglodyne commented
Pushed changes, I think they should address the concerns

2023-07-06 22:28 UTC, merged