Block if grub not installed or config file missing
cpanel/elevate pull request #391
Opened 2024-03-12 00:11 UTC by timmullin

Case RE-83:

Changelog: Block if the grub2-pc package is not installed
  or if the grub.cfg file is missing.

By submitting pull requests to this repo, I agree to the Contributor License Agreement which can be found at: https://github.com/cpanel/elevate/blob/main/docs/cPanel-CLA.pdf

2024-03-12 16:19 UTC, cPholloway requested changes

2024-03-12 16:19 UTC, cPholloway commented on lib/Elevate/Blockers/Grub2.pm
> +    required to upgrade via leapp.
Let's advise them to consider reaching out to support if they hit this blocker.  There is already some wording to do this earlier in this file via `_blocker_grub2_workaround()`

2024-03-12 16:19 UTC, cPholloway commented on lib/Elevate/Blockers/Grub2.pm
> +        The GRUB2 config file is missing.
Let's advise them to consider reaching out to support if they hit this blocker.  There is already some wording to do this earlier in this file via `_blocker_grub2_workaround()`

2024-03-12 16:19 UTC, cPholloway commented on lib/Elevate/Blockers/Grub2.pm
> +    if ( !-e '/boot/grub2/grub.cfg' && !-e '/boot/grub/grub.cfg' ) {
We should use `-f` instead of `-e` here.  Possibly `-s` too to make sure it is not a touch file.

2024-03-13 18:55 UTC, cPholloway approved these changes

2024-03-20 19:04 UTC, toddr approved these changes

2024-03-20 19:05 UTC, merged

2024-03-22 22:33 UTC, annes449 reviewed
QA looks good.

2024-06-14 20:24 UTC, rch77 commented
Now it blocks if there is /boot/efi/EFI/centos/grub.cfg only. I think UEFI systems use /boot/efi/EFI/centos/grub.cfg.
I have added symlink from /boot/grub2/ to ../efi/EFI/centos/grub.cfg but I'm not sure if it'll break something else during the process.
OS: Centos 7.9