Re 421
cpanel/elevate pull request #452
Opened 2024-06-12 18:43 UTC by sfbee

By submitting pull requests to this repo, I agree to the Contributor License Agreement which can be found at: https://github.com/cpanel/elevate/blob/main/docs/cPanel-CLA.pdf

2024-06-12 21:48 UTC, toddr approved these changes

2024-06-12 22:39 UTC, cPholloway requested changes

2024-06-12 22:39 UTC, cPholloway commented on docs-website-src/content/blockers.md
> +On systems configured in this manner, we will offer to automatically assign a custom names (from ethX to cpethX) in the configuration and re-initialize NICs ahead of elevation.
Saying that we block on it, then saying that we offer to automatically update the NIC name is going to be confusing to anyone reading the documention.  I think we should update this section to something similar to the following:

```
### Multiple network interface cards using kernel names

If your machine has multiple network interface cards (NICs) using kernel names (`ethX`), we offer to automatically update the name from `ethX` to `cpethX` during elevation.
  * To find a more in-depth explanation of *why* this name change is necessary, read Freedesktop.org's <a href="https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/" target="_blank">Predictable Network Interface Names</a> documentation.
```

2024-06-12 22:39 UTC, cPholloway commented on docs-website-src/content/blockers.md
> +The system **must** not be set up to use a remote database server. In cases where the system is set up to use a remote server, a local server will be temporarily configured and enabled for the durati
We only do this if the local version of MySQL will be unsupported after the elevation is complete:

```
    # If the database version is supported on the new OS version, then no need to upgrade
    return if Elevate::Database::is_database_version_supported( Elevate::Database::get_local_database_version() );

    $self->_ensure_localhost_mysql_profile_is_active(1);
```

SUGGESTION:

```
### MySQL version

A MySQL upgrade **cannot be** in progress.

If the local version of MySQL/MariaDB installed on the system is not supported on RHEL 8-based distributions, you **must** upgrade to a supported version. If cPanel manages the MySQL installation, we will offer to upgrade MySQL automatically to MariaDB 10.6 during elevation.

**NOTE:** In cases where an upgrade is necessary **and** the system is set up to use a remote server, a local server will be temporarily configured and enabled for the duration of the elevation, and the remote instance will be re-enabled once the elevation completes.
```

2024-06-12 22:41 UTC, cPholloway commented on docs-website-src/content/blockers.md
> +If you are not on a version mentioned in [Latest cPanel & WHM Builds (All Architectures)](http://httpupdate.cpanel.net/) section, run the `/usr/local/cpanel/scripts/upcp` script to update.
Thanks for catching this

2024-06-13 17:21 UTC, kate-official approved these changes
All these changes make sense and look good to me.

2024-06-13 17:48 UTC, cPholloway approved these changes

2024-06-13 17:56 UTC, WriterAmanda approved these changes
The wording looks good 👍

2024-06-26 19:21 UTC, merged