Remove python36 blocker
cpanel/elevate pull request #455
Opened 2024-06-17 18:34 UTC by sfbee

Case RE-336: Remove the python36 blocker, as it has been fixed upstream.

Changelog: Removed python36 blocker on CloudLinux/CentOS 7

By submitting pull requests to this repo, I agree to the Contributor License Agreement which can be found at: https://github.com/cpanel/elevate/blob/main/docs/cPanel-CLA.pdf

2024-06-18 15:48 UTC, cPholloway requested changes

2024-06-18 15:48 UTC, cPholloway commented on lib/Elevate/OS/CloudLinux7.pm
> -use constant leapp_can_handle_python36       => 1;
FIX:  Let's go ahead and kill this key off from `Elevate::OS` completely.

There are two more spots that it needs to be removed from:
```
root@a8 ~/git/elevate (RE-336) # git grep 'leapp_can_handle_python36' lib/ script/
lib/Elevate/OS.pm:        'leapp_can_handle_python36',          # This is used to determine if we can skip the python36 blocker or not
lib/Elevate/OS/RHEL.pm:use constant leapp_can_handle_python36       => 0;
```

2024-06-20 18:15 UTC, cPholloway approved these changes

2024-06-20 18:20 UTC, toddr approved these changes

2024-06-24 22:31 UTC, annes449 approved these changes
All good with QA

2024-06-25 03:49 UTC, merged