Do not block on Panopta or FortiMonitor
cpanel/elevate pull request #498
Opened 2024-08-16 14:59 UTC by timmullin

Case RE-43:

If they have the Panopta agent installed, simply remove it since it is deprecated and will be incompatible with Elevate. Do not block if the FortiMonitor repo is present.

Changelog: No longer block on Panopta or FortiMonitor

By submitting pull requests to this repo, I agree to the Contributor License Agreement which can be found at: https://github.com/cpanel/elevate/blob/main/docs/cPanel-CLA.pdf

2024-08-16 17:55 UTC, cPholloway requested changes

2024-08-16 17:55 UTC, cPholloway commented on lib/Elevate/Components/Panopta.pm
> +use Elevate::StageFile ();
FIX:  Neither of these are used

2024-08-16 17:55 UTC, cPholloway commented on lib/Elevate/Components/Panopta.pm
> +use Log::Log4perl qw(:easy);
FIX:  This module is not used

2024-08-16 18:11 UTC, cPholloway approved these changes

2024-08-19 19:05 UTC, annes449 approved these changes
All good with QA

2024-08-19 22:59 UTC, toddr commented
Asking for final signoff from godaddy on this.

2024-08-20 19:19 UTC, merged