Genericize `--no-leapp`, et al.
cpanel/elevate pull request #508
Opened 2024-09-06 18:48 UTC by sloanebernstein

Case RE-695: Don't assume that leapp will be the only distro upgrade process we will be wrapping.

Changelog: Turn `--no-leapp` into a more generic
 `--upgrade-distro-manually` option, but continue to recognize
 `--no-leapp` as an alias for it.

By submitting pull requests to this repo, I agree to the Contributor License Agreement which can be found at: https://github.com/cpanel/elevate/blob/main/docs/cPanel-CLA.pdf

2024-09-06 20:11 UTC, cPholloway approved these changes
Should probably file a DOCS case for this to review the docs/pod changes, but I'm going to go ahead and approve it

2024-09-10 14:11 UTC, davelcpanelnet requested changes

2024-09-10 14:11 UTC, davelcpanelnet commented on elevate-cpanel
> +        At that stage, the ELevate process is paused, and you can upgrade from 7 to 8 on your own.
Ubuntu versions need represented here.    Maybe we need to check Elevate::OS::instance() or something along those lines and show the appropriate text here.  That or we can simply omit the versions here:

`At that stage, the ELevate process is paused, and you can upgrade to the next distro version on your own.`

2024-09-10 14:11 UTC, davelcpanelnet commented on elevate-cpanel
> +        Once the system has been successfully upgraded from 7 to 8, you can then remove that file
Same as above:

Ubuntu versions need represented here. Maybe we need to check Elevate::OS::instance() or something along those lines and show the appropriate text here. That or we can simply omit the versions here:

At that stage, the ELevate process is paused, and you can upgrade to the next distro version on your own.

2024-09-10 14:11 UTC, davelcpanelnet commented on lib/Elevate/Usage.pm
> +      upgrade-distro-manually no-leapp
s/ no-leapp$//

2024-09-10 14:11 UTC, davelcpanelnet commented on script/elevate-cpanel.PL
> +        At that stage, the ELevate process is paused, and you can upgrade from 7 to 8 on your own.
Again version specifics regarding ubuntu.

2024-09-10 14:30 UTC, davelcpanelnet commented on elevate-cpanel
> +        At that stage, the ELevate process is paused, and you can upgrade from 7 to 8 on your own.
RE-664 looks like it is slated to make the Libs we could rely on for these changes.

Consider any comment here regarding versions for ubuntu in text as gold-plating we have slated for action later.

2024-09-17 19:12 UTC, merged