Get github pruner for elevate-cpanel working
cpanel/elevate pull request #540
Opened 2024-10-30 21:15 UTC by davelcpanelnet

Case RE-924: Get github pruner for elevate-cpanel working

Changelog:

By submitting pull requests to this repo, I agree to the Contributor License Agreement which can be found at: https://github.com/cpanel/elevate/blob/main/docs/cPanel-CLA.pdf

2024-10-31 16:05 UTC, cPholloway requested changes

2024-10-31 16:05 UTC, cPholloway commented on .github/workflows/openstack/prune_openstack
> +            echo "deleting: $ID,$CREATED_DATE,$NAME"s
Stray `s` at the end?

2024-10-31 16:05 UTC, cPholloway commented on .github/workflows/openstack/volume_ids.txt
What is the purpose of adding this touch file? Should we just add the files that prune_openstack creates to .gitignore?

2024-10-31 16:25 UTC, davelcpanelnet commented on .github/workflows/openstack/prune_openstack
> +            echo "deleting: $ID,$CREATED_DATE,$NAME"s
Good catch!

2024-10-31 19:05 UTC, davelcpanelnet commented on .github/workflows/openstack/volume_ids.txt
should be yanked.  Getting that out of there.

2024-11-01 15:26 UTC, toddr approved these changes

2024-11-01 15:26 UTC, merged